version: '3.7'

services:
  db:
    container_name: quizz-db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  web:
    container_name: quizz-web
    build: ./quizz_integration
    volumes: 
      - .:/app
    ports: 
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
